// Code generated by https://github.com/alivers/anchor-go/internal. DO NOT EDIT.

package contract

import ag_solanago "github.com/gagliardetto/solana-go"

var Addresses = map[string]ag_solanago.PublicKey{"11111111111111111111111111111111": ag_solanago.MustPublicKeyFromBase58("11111111111111111111111111111111")}
