// Code generated by https://github.com/alivers/anchor-go/internal. DO NOT EDIT.

package contract

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ChangeAuthority is the `change_authority` instruction.
type ChangeAuthority struct {
	BridgeId       *string
	NewAuthorities *[][33]uint8
	NewNonce       *uint64
	Signature      *[64]uint8
	RecoveryId     *uint8

	// [0] = [WRITE] authority
	//
	// [1] = [WRITE, SIGNER] signer
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewChangeAuthorityInstructionBuilder creates a new `ChangeAuthority` instruction builder.
func NewChangeAuthorityInstructionBuilder() *ChangeAuthority {
	nd := &ChangeAuthority{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetBridgeId sets the "bridge_id" parameter.
func (inst *ChangeAuthority) SetBridgeId(bridge_id string) *ChangeAuthority {
	inst.BridgeId = &bridge_id
	return inst
}

// SetNewAuthorities sets the "new_authorities" parameter.
func (inst *ChangeAuthority) SetNewAuthorities(new_authorities [][33]uint8) *ChangeAuthority {
	inst.NewAuthorities = &new_authorities
	return inst
}

// SetNewNonce sets the "new_nonce" parameter.
func (inst *ChangeAuthority) SetNewNonce(new_nonce uint64) *ChangeAuthority {
	inst.NewNonce = &new_nonce
	return inst
}

// SetSignature sets the "signature" parameter.
func (inst *ChangeAuthority) SetSignature(signature [64]uint8) *ChangeAuthority {
	inst.Signature = &signature
	return inst
}

// SetRecoveryId sets the "recovery_id" parameter.
func (inst *ChangeAuthority) SetRecoveryId(recovery_id uint8) *ChangeAuthority {
	inst.RecoveryId = &recovery_id
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *ChangeAuthority) SetAuthorityAccount(authority ag_solanago.PublicKey) *ChangeAuthority {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).WRITE()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *ChangeAuthority) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst *ChangeAuthority) findAuthorityAddress(bridgeId string, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: 0x617574686f72697479
	seeds = append(seeds, []byte{byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})
	{
		// path: bridge_id
		var res []byte
		res, err = ag_binary.MarshalBorsh(bridgeId)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// findAuthorityAddressWithBumpSeed calculates Authority account address with given seeds and a known bump seed.
// pda program and seeds which refer to the instruction accounts or args should be provided as parameters.
func (inst *ChangeAuthority) findAuthorityAddressWithBumpSeed(bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findAuthorityAddress(bridgeId, bumpSeed)
	return
}
func (inst *ChangeAuthority) MustfindAuthorityAddressWithBumpSeed(bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findAuthorityAddress(bridgeId, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAuthorityAddress finds Authority account address with given seeds.
func (inst *ChangeAuthority) FindAuthorityAddress(bridgeId string) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findAuthorityAddress(bridgeId, 0)
	return
}
func (inst *ChangeAuthority) MustFindAuthorityAddress(bridgeId string) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findAuthorityAddress(bridgeId, 0)
	if err != nil {
		panic(err)
	}
	return
}

// SetSignerAccount sets the "signer" account.
func (inst *ChangeAuthority) SetSignerAccount(signer ag_solanago.PublicKey) *ChangeAuthority {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *ChangeAuthority) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst ChangeAuthority) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ChangeAuthority,
	}}
}

func (inst *ChangeAuthority) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeId == nil {
			return errors.New("BridgeId parameter is not set")
		}
		if inst.NewAuthorities == nil {
			return errors.New("NewAuthorities parameter is not set")
		}
		if inst.NewNonce == nil {
			return errors.New("NewNonce parameter is not set")
		}
		if inst.Signature == nil {
			return errors.New("Signature parameter is not set")
		}
		if inst.RecoveryId == nil {
			return errors.New("RecoveryId parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Signer is not set")
		}
	}
	return nil
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ChangeAuthority) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ChangeAuthority) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ChangeAuthority")).
				ParentFunc(func(instructionBranch ag_treeout.Branches) {
					// Parameters of the instruction:
					instructionBranch.Child("Params[len=5]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("       BridgeId", *inst.BridgeId))
						paramsBranch.Child(ag_format.Param(" NewAuthorities", *inst.NewAuthorities))
						paramsBranch.Child(ag_format.Param("       NewNonce", *inst.NewNonce))
						paramsBranch.Child(ag_format.Param("      Signature", *inst.Signature))
						paramsBranch.Child(ag_format.Param("     RecoveryId", *inst.RecoveryId))
					})
					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   signer", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj ChangeAuthority) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeId` param:
	err = encoder.Encode(obj.BridgeId)
	if err != nil {
		return err
	}
	// Serialize `NewAuthorities` param:
	err = encoder.Encode(obj.NewAuthorities)
	if err != nil {
		return err
	}
	// Serialize `NewNonce` param:
	err = encoder.Encode(obj.NewNonce)
	if err != nil {
		return err
	}
	// Serialize `Signature` param:
	err = encoder.Encode(obj.Signature)
	if err != nil {
		return err
	}
	// Serialize `RecoveryId` param:
	err = encoder.Encode(obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}

func (obj *ChangeAuthority) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeId`:
	err = decoder.Decode(&obj.BridgeId)
	if err != nil {
		return err
	}
	// Deserialize `NewAuthorities`:
	err = decoder.Decode(&obj.NewAuthorities)
	if err != nil {
		return err
	}
	// Deserialize `NewNonce`:
	err = decoder.Decode(&obj.NewNonce)
	if err != nil {
		return err
	}
	// Deserialize `Signature`:
	err = decoder.Decode(&obj.Signature)
	if err != nil {
		return err
	}
	// Deserialize `RecoveryId`:
	err = decoder.Decode(&obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}

// NewChangeAuthorityInstruction declares a new ChangeAuthority instruction with the provided parameters and accounts.
func NewChangeAuthorityInstruction(
	// Parameters:
	bridge_id string,
	new_authorities [][33]uint8,
	new_nonce uint64,
	signature [64]uint8,
	recovery_id uint8,
	// Accounts:
	authority ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
) *ChangeAuthority {
	return NewChangeAuthorityInstructionBuilder().
		SetBridgeId(bridge_id).
		SetNewAuthorities(new_authorities).
		SetNewNonce(new_nonce).
		SetSignature(signature).
		SetRecoveryId(recovery_id).
		SetAuthorityAccount(authority).
		SetSignerAccount(signer)
}
