// Code generated by https://github.com/alivers/anchor-go/internal. DO NOT EDIT.

package contract

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// DepositSpl is the `deposit_spl` instruction.
type DepositSpl struct {
	BridgeId   *string
	Amount     *uint64
	ChainId    *string
	Address    *string
	ReferralId *uint16

	// [0] = [] mint
	//
	// [1] = [WRITE] spl_vault
	//
	// [2] = [WRITE] sender
	//
	// [3] = [WRITE, SIGNER] signer
	//
	// [4] = [] token_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewDepositSplInstructionBuilder creates a new `DepositSpl` instruction builder.
func NewDepositSplInstructionBuilder() *DepositSpl {
	nd := &DepositSpl{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	return nd
}

// SetBridgeId sets the "bridge_id" parameter.
func (inst *DepositSpl) SetBridgeId(bridge_id string) *DepositSpl {
	inst.BridgeId = &bridge_id
	return inst
}

// SetAmount sets the "amount" parameter.
func (inst *DepositSpl) SetAmount(amount uint64) *DepositSpl {
	inst.Amount = &amount
	return inst
}

// SetChainId sets the "chain_id" parameter.
func (inst *DepositSpl) SetChainId(chain_id string) *DepositSpl {
	inst.ChainId = &chain_id
	return inst
}

// SetAddress sets the "address" parameter.
func (inst *DepositSpl) SetAddress(address string) *DepositSpl {
	inst.Address = &address
	return inst
}

// SetReferralId sets the "referral_id" parameter.
func (inst *DepositSpl) SetReferralId(referral_id uint16) *DepositSpl {
	inst.ReferralId = &referral_id
	return inst
}

// SetMintAccount sets the "mint" account.
func (inst *DepositSpl) SetMintAccount(mint ag_solanago.PublicKey) *DepositSpl {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *DepositSpl) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSplVaultAccount sets the "spl_vault" account.
func (inst *DepositSpl) SetSplVaultAccount(splVault ag_solanago.PublicKey) *DepositSpl {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(splVault).WRITE()
	return inst
}

// GetSplVaultAccount gets the "spl_vault" account.
func (inst *DepositSpl) GetSplVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst *DepositSpl) findSplVaultAddress(mint ag_solanago.PublicKey, bridgeId string, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: 0x7661756c74
	seeds = append(seeds, []byte{byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	seeds = append(seeds, mint.Bytes())
	{
		// path: bridge_id
		var res []byte
		res, err = ag_binary.MarshalBorsh(bridgeId)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// findSplVaultAddressWithBumpSeed calculates SplVault account address with given seeds and a known bump seed.
// pda program and seeds which refer to the instruction accounts or args should be provided as parameters.
func (inst *DepositSpl) findSplVaultAddressWithBumpSeed(mint ag_solanago.PublicKey, bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findSplVaultAddress(mint, bridgeId, bumpSeed)
	return
}
func (inst *DepositSpl) MustfindSplVaultAddressWithBumpSeed(mint ag_solanago.PublicKey, bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findSplVaultAddress(mint, bridgeId, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindSplVaultAddress finds SplVault account address with given seeds.
func (inst *DepositSpl) FindSplVaultAddress(mint ag_solanago.PublicKey, bridgeId string) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findSplVaultAddress(mint, bridgeId, 0)
	return
}
func (inst *DepositSpl) MustFindSplVaultAddress(mint ag_solanago.PublicKey, bridgeId string) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findSplVaultAddress(mint, bridgeId, 0)
	if err != nil {
		panic(err)
	}
	return
}

// SetSenderAccount sets the "sender" account.
func (inst *DepositSpl) SetSenderAccount(sender ag_solanago.PublicKey) *DepositSpl {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(sender).WRITE()
	return inst
}

// GetSenderAccount gets the "sender" account.
func (inst *DepositSpl) GetSenderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSignerAccount sets the "signer" account.
func (inst *DepositSpl) SetSignerAccount(signer ag_solanago.PublicKey) *DepositSpl {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *DepositSpl) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *DepositSpl) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *DepositSpl {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *DepositSpl) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

func (inst DepositSpl) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_DepositSpl,
	}}
}

func (inst *DepositSpl) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeId == nil {
			return errors.New("BridgeId parameter is not set")
		}
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
		if inst.ChainId == nil {
			return errors.New("ChainId parameter is not set")
		}
		if inst.Address == nil {
			return errors.New("Address parameter is not set")
		}
		if inst.ReferralId == nil {
			return errors.New("ReferralId parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SplVault is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Sender is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst DepositSpl) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *DepositSpl) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("DepositSpl")).
				ParentFunc(func(instructionBranch ag_treeout.Branches) {
					// Parameters of the instruction:
					instructionBranch.Child("Params[len=5]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   BridgeId", *inst.BridgeId))
						paramsBranch.Child(ag_format.Param("     Amount", *inst.Amount))
						paramsBranch.Child(ag_format.Param("    ChainId", *inst.ChainId))
						paramsBranch.Child(ag_format.Param("    Address", *inst.Address))
						paramsBranch.Child(ag_format.Param(" ReferralId", *inst.ReferralId))
					})
					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         mint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    spl_vault", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       sender", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("       signer", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("token_program", inst.AccountMetaSlice.Get(4)))
					})
				})
		})
}

func (obj DepositSpl) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeId` param:
	err = encoder.Encode(obj.BridgeId)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `ChainId` param:
	err = encoder.Encode(obj.ChainId)
	if err != nil {
		return err
	}
	// Serialize `Address` param:
	err = encoder.Encode(obj.Address)
	if err != nil {
		return err
	}
	// Serialize `ReferralId` param:
	err = encoder.Encode(obj.ReferralId)
	if err != nil {
		return err
	}
	return nil
}

func (obj *DepositSpl) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeId`:
	err = decoder.Decode(&obj.BridgeId)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `ChainId`:
	err = decoder.Decode(&obj.ChainId)
	if err != nil {
		return err
	}
	// Deserialize `Address`:
	err = decoder.Decode(&obj.Address)
	if err != nil {
		return err
	}
	// Deserialize `ReferralId`:
	err = decoder.Decode(&obj.ReferralId)
	if err != nil {
		return err
	}
	return nil
}

// NewDepositSplInstruction declares a new DepositSpl instruction with the provided parameters and accounts.
func NewDepositSplInstruction(
	// Parameters:
	bridge_id string,
	amount uint64,
	chain_id string,
	address string,
	referral_id uint16,
	// Accounts:
	mint ag_solanago.PublicKey,
	splVault ag_solanago.PublicKey,
	sender ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
) *DepositSpl {
	return NewDepositSplInstructionBuilder().
		SetBridgeId(bridge_id).
		SetAmount(amount).
		SetChainId(chain_id).
		SetAddress(address).
		SetReferralId(referral_id).
		SetMintAccount(mint).
		SetSplVaultAccount(splVault).
		SetSenderAccount(sender).
		SetSignerAccount(signer).
		SetTokenProgramAccount(tokenProgram)
}
