// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package contract

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// DepositSpl is the `deposit_spl` instruction.
type DepositSplInstruction struct {
	BridgeId *string
	Amount   *uint64
	ChainId  *string
	Address  *string

	// [0] = [] mint
	//
	// [1] = [WRITE] spl_vault
	//
	// [2] = [WRITE] sender
	//
	// [3] = [WRITE, SIGNER] signer
	//
	// [4] = [] token_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewDepositSplInstructionBuilder creates a new `DepositSplInstruction` instruction builder.
func NewDepositSplInstructionBuilder() *DepositSplInstruction {
	nd := &DepositSplInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	return nd
}

// SetBridgeId sets the "bridge_id" parameter.
func (inst *DepositSplInstruction) SetBridgeId(bridge_id string) *DepositSplInstruction {
	inst.BridgeId = &bridge_id
	return inst
}

// SetAmount sets the "amount" parameter.
func (inst *DepositSplInstruction) SetAmount(amount uint64) *DepositSplInstruction {
	inst.Amount = &amount
	return inst
}

// SetChainId sets the "chain_id" parameter.
func (inst *DepositSplInstruction) SetChainId(chain_id string) *DepositSplInstruction {
	inst.ChainId = &chain_id
	return inst
}

// SetAddress sets the "address" parameter.
func (inst *DepositSplInstruction) SetAddress(address string) *DepositSplInstruction {
	inst.Address = &address
	return inst
}

// SetMintAccount sets the "mint" account.
func (inst *DepositSplInstruction) SetMintAccount(mint ag_solanago.PublicKey) *DepositSplInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *DepositSplInstruction) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSplVaultAccount sets the "spl_vault" account.
func (inst *DepositSplInstruction) SetSplVaultAccount(splVault ag_solanago.PublicKey) *DepositSplInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(splVault).WRITE()
	return inst
}

func (inst *DepositSplInstruction) findFindSplVaultAddress(mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: vault
	seeds = append(seeds, []byte{byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	// path: mint
	seeds = append(seeds, mint.Bytes())
	// arg: BridgeId
	bridgeIdSeed, err := ag_binary.MarshalBorsh(inst.BridgeId)
	if err != nil {
		return
	}
	seeds = append(seeds, bridgeIdSeed)

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindSplVaultAddressWithBumpSeed calculates SplVault account address with given seeds and a known bump seed.
func (inst *DepositSplInstruction) FindSplVaultAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindSplVaultAddress(mint, bumpSeed)
	return
}

func (inst *DepositSplInstruction) MustFindSplVaultAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSplVaultAddress(mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindSplVaultAddress finds SplVault account address with given seeds.
func (inst *DepositSplInstruction) FindSplVaultAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindSplVaultAddress(mint, 0)
	return
}

func (inst *DepositSplInstruction) MustFindSplVaultAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSplVaultAddress(mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetSplVaultAccount gets the "spl_vault" account.
func (inst *DepositSplInstruction) GetSplVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSenderAccount sets the "sender" account.
func (inst *DepositSplInstruction) SetSenderAccount(sender ag_solanago.PublicKey) *DepositSplInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(sender).WRITE()
	return inst
}

// GetSenderAccount gets the "sender" account.
func (inst *DepositSplInstruction) GetSenderAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSignerAccount sets the "signer" account.
func (inst *DepositSplInstruction) SetSignerAccount(signer ag_solanago.PublicKey) *DepositSplInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *DepositSplInstruction) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *DepositSplInstruction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *DepositSplInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *DepositSplInstruction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

func (inst DepositSplInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_DepositSpl,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst DepositSplInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *DepositSplInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeId == nil {
			return errors.New("BridgeId parameter is not set")
		}
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
		if inst.ChainId == nil {
			return errors.New("ChainId parameter is not set")
		}
		if inst.Address == nil {
			return errors.New("Address parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SplVault is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Sender is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *DepositSplInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("DepositSpl")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=4]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" BridgeId", *inst.BridgeId))
						paramsBranch.Child(ag_format.Param("   Amount", *inst.Amount))
						paramsBranch.Child(ag_format.Param("  ChainId", *inst.ChainId))
						paramsBranch.Child(ag_format.Param("  Address", *inst.Address))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         mint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    spl_vault", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       sender", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("       signer", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("token_program", inst.AccountMetaSlice.Get(4)))
					})
				})
		})
}

func (obj DepositSplInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeId` param:
	err = encoder.Encode(obj.BridgeId)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `ChainId` param:
	err = encoder.Encode(obj.ChainId)
	if err != nil {
		return err
	}
	// Serialize `Address` param:
	err = encoder.Encode(obj.Address)
	if err != nil {
		return err
	}
	return nil
}
func (obj *DepositSplInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeId`:
	err = decoder.Decode(&obj.BridgeId)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `ChainId`:
	err = decoder.Decode(&obj.ChainId)
	if err != nil {
		return err
	}
	// Deserialize `Address`:
	err = decoder.Decode(&obj.Address)
	if err != nil {
		return err
	}
	return nil
}

// NewDepositSplInstruction declares a new DepositSpl instruction with the provided parameters and accounts.
func NewDepositSplInstruction(
	// Parameters:
	bridge_id string,
	amount uint64,
	chain_id string,
	address string,
	// Accounts:
	mint ag_solanago.PublicKey,
	splVault ag_solanago.PublicKey,
	sender ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *DepositSplInstruction {
	return NewDepositSplInstructionBuilder().
		SetBridgeId(bridge_id).
		SetAmount(amount).
		SetChainId(chain_id).
		SetAddress(address).
		SetMintAccount(mint).
		SetSplVaultAccount(splVault).
		SetSenderAccount(sender).
		SetSignerAccount(signer).
		SetTokenProgramAccount(tokenProgram)
}
