// Code generated by https://github.com/alivers/anchor-go/internal. DO NOT EDIT.

package contract

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// InitWrappedMint is the `init_wrapped_mint` instruction.
type InitWrappedMint struct {
	BridgeId  *string
	Decimals  *uint8
	MintNonce *uint64
	Symbol    *string
	Name      *string
	Uri       *string

	// [0] = [WRITE] mint
	//
	// [1] = [WRITE, SIGNER] signer
	//
	// [2] = [] token_program
	//
	// [3] = [] system_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewInitWrappedMintInstructionBuilder creates a new `InitWrappedMint` instruction builder.
func NewInitWrappedMintInstructionBuilder() *InitWrappedMint {
	nd := &InitWrappedMint{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	nd.AccountMetaSlice[3] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	return nd
}

// SetBridgeId sets the "bridge_id" parameter.
func (inst *InitWrappedMint) SetBridgeId(bridge_id string) *InitWrappedMint {
	inst.BridgeId = &bridge_id
	return inst
}

// SetDecimals sets the "decimals" parameter.
func (inst *InitWrappedMint) SetDecimals(decimals uint8) *InitWrappedMint {
	inst.Decimals = &decimals
	return inst
}

// SetMintNonce sets the "mint_nonce" parameter.
func (inst *InitWrappedMint) SetMintNonce(mint_nonce uint64) *InitWrappedMint {
	inst.MintNonce = &mint_nonce
	return inst
}

// SetSymbol sets the "symbol" parameter.
func (inst *InitWrappedMint) SetSymbol(symbol string) *InitWrappedMint {
	inst.Symbol = &symbol
	return inst
}

// SetName sets the "name" parameter.
func (inst *InitWrappedMint) SetName(name string) *InitWrappedMint {
	inst.Name = &name
	return inst
}

// SetUri sets the "uri" parameter.
func (inst *InitWrappedMint) SetUri(uri string) *InitWrappedMint {
	inst.Uri = &uri
	return inst
}

// SetMintAccount sets the "mint" account.
func (inst *InitWrappedMint) SetMintAccount(mint ag_solanago.PublicKey) *InitWrappedMint {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(mint).WRITE()
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *InitWrappedMint) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst *InitWrappedMint) findMintAddress(symbol string, mintNonce uint64, bridgeId string, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: 0x6d696e74
	seeds = append(seeds, []byte{byte(0x6d), byte(0x69), byte(0x6e), byte(0x74)})
	{
		// path: symbol
		var res []byte
		res, err = ag_binary.MarshalBorsh(symbol)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}
	{
		// path: mint_nonce
		var res []byte
		res, err = ag_binary.MarshalBorsh(mintNonce)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}
	{
		// path: bridge_id
		var res []byte
		res, err = ag_binary.MarshalBorsh(bridgeId)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// findMintAddressWithBumpSeed calculates Mint account address with given seeds and a known bump seed.
// pda program and seeds which refer to the instruction accounts or args should be provided as parameters.
func (inst *InitWrappedMint) findMintAddressWithBumpSeed(symbol string, mintNonce uint64, bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findMintAddress(symbol, mintNonce, bridgeId, bumpSeed)
	return
}
func (inst *InitWrappedMint) MustfindMintAddressWithBumpSeed(symbol string, mintNonce uint64, bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findMintAddress(symbol, mintNonce, bridgeId, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindMintAddress finds Mint account address with given seeds.
func (inst *InitWrappedMint) FindMintAddress(symbol string, mintNonce uint64, bridgeId string) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findMintAddress(symbol, mintNonce, bridgeId, 0)
	return
}
func (inst *InitWrappedMint) MustFindMintAddress(symbol string, mintNonce uint64, bridgeId string) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findMintAddress(symbol, mintNonce, bridgeId, 0)
	if err != nil {
		panic(err)
	}
	return
}

// SetSignerAccount sets the "signer" account.
func (inst *InitWrappedMint) SetSignerAccount(signer ag_solanago.PublicKey) *InitWrappedMint {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *InitWrappedMint) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *InitWrappedMint) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *InitWrappedMint {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *InitWrappedMint) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *InitWrappedMint) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *InitWrappedMint {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *InitWrappedMint) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst InitWrappedMint) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_InitWrappedMint,
	}}
}

func (inst *InitWrappedMint) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeId == nil {
			return errors.New("BridgeId parameter is not set")
		}
		if inst.Decimals == nil {
			return errors.New("Decimals parameter is not set")
		}
		if inst.MintNonce == nil {
			return errors.New("MintNonce parameter is not set")
		}
		if inst.Symbol == nil {
			return errors.New("Symbol parameter is not set")
		}
		if inst.Name == nil {
			return errors.New("Name parameter is not set")
		}
		if inst.Uri == nil {
			return errors.New("Uri parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst InitWrappedMint) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *InitWrappedMint) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("InitWrappedMint")).
				ParentFunc(func(instructionBranch ag_treeout.Branches) {
					// Parameters of the instruction:
					instructionBranch.Child("Params[len=6]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("  BridgeId", *inst.BridgeId))
						paramsBranch.Child(ag_format.Param("  Decimals", *inst.Decimals))
						paramsBranch.Child(ag_format.Param(" MintNonce", *inst.MintNonce))
						paramsBranch.Child(ag_format.Param("    Symbol", *inst.Symbol))
						paramsBranch.Child(ag_format.Param("      Name", *inst.Name))
						paramsBranch.Child(ag_format.Param("       Uri", *inst.Uri))
					})
					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          mint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        signer", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta(" token_program", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("system_program", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj InitWrappedMint) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeId` param:
	err = encoder.Encode(obj.BridgeId)
	if err != nil {
		return err
	}
	// Serialize `Decimals` param:
	err = encoder.Encode(obj.Decimals)
	if err != nil {
		return err
	}
	// Serialize `MintNonce` param:
	err = encoder.Encode(obj.MintNonce)
	if err != nil {
		return err
	}
	// Serialize `Symbol` param:
	err = encoder.Encode(obj.Symbol)
	if err != nil {
		return err
	}
	// Serialize `Name` param:
	err = encoder.Encode(obj.Name)
	if err != nil {
		return err
	}
	// Serialize `Uri` param:
	err = encoder.Encode(obj.Uri)
	if err != nil {
		return err
	}
	return nil
}

func (obj *InitWrappedMint) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeId`:
	err = decoder.Decode(&obj.BridgeId)
	if err != nil {
		return err
	}
	// Deserialize `Decimals`:
	err = decoder.Decode(&obj.Decimals)
	if err != nil {
		return err
	}
	// Deserialize `MintNonce`:
	err = decoder.Decode(&obj.MintNonce)
	if err != nil {
		return err
	}
	// Deserialize `Symbol`:
	err = decoder.Decode(&obj.Symbol)
	if err != nil {
		return err
	}
	// Deserialize `Name`:
	err = decoder.Decode(&obj.Name)
	if err != nil {
		return err
	}
	// Deserialize `Uri`:
	err = decoder.Decode(&obj.Uri)
	if err != nil {
		return err
	}
	return nil
}

// NewInitWrappedMintInstruction declares a new InitWrappedMint instruction with the provided parameters and accounts.
func NewInitWrappedMintInstruction(
	// Parameters:
	bridge_id string,
	decimals uint8,
	mint_nonce uint64,
	symbol string,
	name string,
	uri string,
	// Accounts:
	mint ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
) *InitWrappedMint {
	return NewInitWrappedMintInstructionBuilder().
		SetBridgeId(bridge_id).
		SetDecimals(decimals).
		SetMintNonce(mint_nonce).
		SetSymbol(symbol).
		SetName(name).
		SetUri(uri).
		SetMintAccount(mint).
		SetSignerAccount(signer).
		SetTokenProgramAccount(tokenProgram).
		SetSystemProgramAccount(systemProgram)
}
