// Code generated by https://github.com/alivers/anchor-go/internal. DO NOT EDIT.

package contract

import ag_binary "github.com/gagliardetto/binary"

type Authority struct {
	Bump      uint8
	Signers   [][33]uint8
	AuthNonce uint64
}

func (obj Authority) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Bump` param:
	err = encoder.Encode(obj.Bump)
	if err != nil {
		return err
	}
	// Serialize `Signers` param:
	err = encoder.Encode(obj.Signers)
	if err != nil {
		return err
	}
	// Serialize `AuthNonce` param:
	err = encoder.Encode(obj.AuthNonce)
	if err != nil {
		return err
	}
	return nil
}

func (obj *Authority) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Bump`:
	err = decoder.Decode(&obj.Bump)
	if err != nil {
		return err
	}
	// Deserialize `Signers`:
	err = decoder.Decode(&obj.Signers)
	if err != nil {
		return err
	}
	// Deserialize `AuthNonce`:
	err = decoder.Decode(&obj.AuthNonce)
	if err != nil {
		return err
	}
	return nil
}

type TxUsed struct {
	Used bool
}

func (obj TxUsed) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Used` param:
	err = encoder.Encode(obj.Used)
	if err != nil {
		return err
	}
	return nil
}

func (obj *TxUsed) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Used`:
	if !decoder.HasRemaining() {
		return nil
	}
	err = decoder.Decode(&obj.Used)
	if err != nil {
		return err
	}
	return nil
}
