// Code generated by https://github.com/alivers/anchor-go/internal. DO NOT EDIT.

package contract

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UpdateSigner is the `update_signer` instruction.
type UpdateSigner struct {
	BridgeId       *string
	RequestType    *UpdateSignerRequestType
	Signer         *[33]uint8
	StartTimestamp *int64
	EndTimestamp   *int64
	NewNonce       *uint64
	Signature      *[64]uint8
	RecoveryId     *uint8

	// [0] = [WRITE] authority
	//
	// [1] = [WRITE, SIGNER] signer
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateSignerInstructionBuilder creates a new `UpdateSigner` instruction builder.
func NewUpdateSignerInstructionBuilder() *UpdateSigner {
	nd := &UpdateSigner{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetBridgeId sets the "bridge_id" parameter.
func (inst *UpdateSigner) SetBridgeId(bridge_id string) *UpdateSigner {
	inst.BridgeId = &bridge_id
	return inst
}

// SetRequestType sets the "request_type" parameter.
func (inst *UpdateSigner) SetRequestType(request_type UpdateSignerRequestType) *UpdateSigner {
	inst.RequestType = &request_type
	return inst
}

// SetSigner sets the "signer" parameter.
func (inst *UpdateSigner) SetSigner(signer [33]uint8) *UpdateSigner {
	inst.Signer = &signer
	return inst
}

// SetStartTimestamp sets the "start_timestamp" parameter.
func (inst *UpdateSigner) SetStartTimestamp(start_timestamp int64) *UpdateSigner {
	inst.StartTimestamp = &start_timestamp
	return inst
}

// SetEndTimestamp sets the "end_timestamp" parameter.
func (inst *UpdateSigner) SetEndTimestamp(end_timestamp int64) *UpdateSigner {
	inst.EndTimestamp = &end_timestamp
	return inst
}

// SetNewNonce sets the "new_nonce" parameter.
func (inst *UpdateSigner) SetNewNonce(new_nonce uint64) *UpdateSigner {
	inst.NewNonce = &new_nonce
	return inst
}

// SetSignature sets the "signature" parameter.
func (inst *UpdateSigner) SetSignature(signature [64]uint8) *UpdateSigner {
	inst.Signature = &signature
	return inst
}

// SetRecoveryId sets the "recovery_id" parameter.
func (inst *UpdateSigner) SetRecoveryId(recovery_id uint8) *UpdateSigner {
	inst.RecoveryId = &recovery_id
	return inst
}

// SetAuthorityAccount sets the "authority" account.
func (inst *UpdateSigner) SetAuthorityAccount(authority ag_solanago.PublicKey) *UpdateSigner {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(authority).WRITE()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *UpdateSigner) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst *UpdateSigner) findAuthorityAddress(bridgeId string, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: 0x617574686f72697479
	seeds = append(seeds, []byte{byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})
	{
		// path: bridge_id
		var res []byte
		res, err = ag_binary.MarshalBorsh(bridgeId)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// findAuthorityAddressWithBumpSeed calculates Authority account address with given seeds and a known bump seed.
// pda program and seeds which refer to the instruction accounts or args should be provided as parameters.
func (inst *UpdateSigner) findAuthorityAddressWithBumpSeed(bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findAuthorityAddress(bridgeId, bumpSeed)
	return
}
func (inst *UpdateSigner) MustfindAuthorityAddressWithBumpSeed(bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findAuthorityAddress(bridgeId, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAuthorityAddress finds Authority account address with given seeds.
func (inst *UpdateSigner) FindAuthorityAddress(bridgeId string) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findAuthorityAddress(bridgeId, 0)
	return
}
func (inst *UpdateSigner) MustFindAuthorityAddress(bridgeId string) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findAuthorityAddress(bridgeId, 0)
	if err != nil {
		panic(err)
	}
	return
}

// SetSignerAccount sets the "signer" account.
func (inst *UpdateSigner) SetSignerAccount(signer ag_solanago.PublicKey) *UpdateSigner {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *UpdateSigner) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst UpdateSigner) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateSigner,
	}}
}

func (inst *UpdateSigner) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeId == nil {
			return errors.New("BridgeId parameter is not set")
		}
		if inst.RequestType == nil {
			return errors.New("RequestType parameter is not set")
		}
		if inst.Signer == nil {
			return errors.New("Signer parameter is not set")
		}
		if inst.StartTimestamp == nil {
			return errors.New("StartTimestamp parameter is not set")
		}
		if inst.EndTimestamp == nil {
			return errors.New("EndTimestamp parameter is not set")
		}
		if inst.NewNonce == nil {
			return errors.New("NewNonce parameter is not set")
		}
		if inst.Signature == nil {
			return errors.New("Signature parameter is not set")
		}
		if inst.RecoveryId == nil {
			return errors.New("RecoveryId parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Signer is not set")
		}
	}
	return nil
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateSigner) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateSigner) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateSigner")).
				ParentFunc(func(instructionBranch ag_treeout.Branches) {
					// Parameters of the instruction:
					instructionBranch.Child("Params[len=8]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("       BridgeId", *inst.BridgeId))
						paramsBranch.Child(ag_format.Param("    RequestType", *inst.RequestType))
						paramsBranch.Child(ag_format.Param("         Signer", *inst.Signer))
						paramsBranch.Child(ag_format.Param(" StartTimestamp", *inst.StartTimestamp))
						paramsBranch.Child(ag_format.Param("   EndTimestamp", *inst.EndTimestamp))
						paramsBranch.Child(ag_format.Param("       NewNonce", *inst.NewNonce))
						paramsBranch.Child(ag_format.Param("      Signature", *inst.Signature))
						paramsBranch.Child(ag_format.Param("     RecoveryId", *inst.RecoveryId))
					})
					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("authority", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("   signer", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj UpdateSigner) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeId` param:
	err = encoder.Encode(obj.BridgeId)
	if err != nil {
		return err
	}
	// Serialize `RequestType` param:
	err = encoder.Encode(obj.RequestType)
	if err != nil {
		return err
	}
	// Serialize `Signer` param:
	err = encoder.Encode(obj.Signer)
	if err != nil {
		return err
	}
	// Serialize `StartTimestamp` param:
	err = encoder.Encode(obj.StartTimestamp)
	if err != nil {
		return err
	}
	// Serialize `EndTimestamp` param:
	err = encoder.Encode(obj.EndTimestamp)
	if err != nil {
		return err
	}
	// Serialize `NewNonce` param:
	err = encoder.Encode(obj.NewNonce)
	if err != nil {
		return err
	}
	// Serialize `Signature` param:
	err = encoder.Encode(obj.Signature)
	if err != nil {
		return err
	}
	// Serialize `RecoveryId` param:
	err = encoder.Encode(obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}

func (obj *UpdateSigner) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeId`:
	err = decoder.Decode(&obj.BridgeId)
	if err != nil {
		return err
	}
	// Deserialize `RequestType`:
	err = decoder.Decode(&obj.RequestType)
	if err != nil {
		return err
	}
	// Deserialize `Signer`:
	err = decoder.Decode(&obj.Signer)
	if err != nil {
		return err
	}
	// Deserialize `StartTimestamp`:
	err = decoder.Decode(&obj.StartTimestamp)
	if err != nil {
		return err
	}
	// Deserialize `EndTimestamp`:
	err = decoder.Decode(&obj.EndTimestamp)
	if err != nil {
		return err
	}
	// Deserialize `NewNonce`:
	err = decoder.Decode(&obj.NewNonce)
	if err != nil {
		return err
	}
	// Deserialize `Signature`:
	err = decoder.Decode(&obj.Signature)
	if err != nil {
		return err
	}
	// Deserialize `RecoveryId`:
	err = decoder.Decode(&obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}

// NewUpdateSignerInstruction declares a new UpdateSigner instruction with the provided parameters and accounts.
func NewUpdateSignerInstruction(
	// Parameters:
	bridge_id string,
	request_type UpdateSignerRequestType,
	signer [33]uint8,
	start_timestamp int64,
	end_timestamp int64,
	new_nonce uint64,
	signature [64]uint8,
	recovery_id uint8,
	// Accounts:
	authority ag_solanago.PublicKey,
	signerAccount ag_solanago.PublicKey,
) *UpdateSigner {
	return NewUpdateSignerInstructionBuilder().
		SetBridgeId(bridge_id).
		SetRequestType(request_type).
		SetSigner(signer).
		SetStartTimestamp(start_timestamp).
		SetEndTimestamp(end_timestamp).
		SetNewNonce(new_nonce).
		SetSignature(signature).
		SetRecoveryId(recovery_id).
		SetAuthorityAccount(authority).
		SetSignerAccount(signerAccount)
}
