// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package contract

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// WithdrawNative is the `withdraw_native` instruction.
type WithdrawNativeInstruction struct {
	BridgeId   *string
	Hash       *[32]uint8
	Amount     *uint64
	Nonce      *uint64
	Signature  *[64]uint8
	RecoveryId *uint8

	// [0] = [WRITE] receiver
	//
	// [1] = [WRITE] authority
	//
	// [2] = [WRITE] tx_used
	//
	// [3] = [WRITE, SIGNER] signer
	//
	// [4] = [] system_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewWithdrawNativeInstructionBuilder creates a new `WithdrawNativeInstruction` instruction builder.
func NewWithdrawNativeInstructionBuilder() *WithdrawNativeInstruction {
	nd := &WithdrawNativeInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 5),
	}
	nd.AccountMetaSlice[4] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	return nd
}

// SetBridgeId sets the "bridge_id" parameter.
func (inst *WithdrawNativeInstruction) SetBridgeId(bridge_id string) *WithdrawNativeInstruction {
	inst.BridgeId = &bridge_id
	return inst
}

// SetHash sets the "hash" parameter.
func (inst *WithdrawNativeInstruction) SetHash(hash [32]uint8) *WithdrawNativeInstruction {
	inst.Hash = &hash
	return inst
}

// SetAmount sets the "amount" parameter.
func (inst *WithdrawNativeInstruction) SetAmount(amount uint64) *WithdrawNativeInstruction {
	inst.Amount = &amount
	return inst
}

// SetNonce sets the "nonce" parameter.
func (inst *WithdrawNativeInstruction) SetNonce(nonce uint64) *WithdrawNativeInstruction {
	inst.Nonce = &nonce
	return inst
}

// SetSignature sets the "signature" parameter.
func (inst *WithdrawNativeInstruction) SetSignature(signature [64]uint8) *WithdrawNativeInstruction {
	inst.Signature = &signature
	return inst
}

// SetRecoveryId sets the "recovery_id" parameter.
func (inst *WithdrawNativeInstruction) SetRecoveryId(recovery_id uint8) *WithdrawNativeInstruction {
	inst.RecoveryId = &recovery_id
	return inst
}

// SetReceiverAccount sets the "receiver" account.
func (inst *WithdrawNativeInstruction) SetReceiverAccount(receiver ag_solanago.PublicKey) *WithdrawNativeInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(receiver).WRITE()
	return inst
}

// GetReceiverAccount gets the "receiver" account.
func (inst *WithdrawNativeInstruction) GetReceiverAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *WithdrawNativeInstruction) SetAuthorityAccount(authority ag_solanago.PublicKey) *WithdrawNativeInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).WRITE()
	return inst
}

func (inst *WithdrawNativeInstruction) findFindAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: authority
	seeds = append(seeds, []byte{byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})
	// arg: BridgeId
	bridgeIdSeed, err := ag_binary.MarshalBorsh(inst.BridgeId)
	if err != nil {
		return
	}
	seeds = append(seeds, bridgeIdSeed)

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindAuthorityAddressWithBumpSeed calculates Authority account address with given seeds and a known bump seed.
func (inst *WithdrawNativeInstruction) FindAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindAuthorityAddress(bumpSeed)
	return
}

func (inst *WithdrawNativeInstruction) MustFindAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAuthorityAddress finds Authority account address with given seeds.
func (inst *WithdrawNativeInstruction) FindAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindAuthorityAddress(0)
	return
}

func (inst *WithdrawNativeInstruction) MustFindAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetAuthorityAccount gets the "authority" account.
func (inst *WithdrawNativeInstruction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetTxUsedAccount sets the "tx_used" account.
func (inst *WithdrawNativeInstruction) SetTxUsedAccount(txUsed ag_solanago.PublicKey) *WithdrawNativeInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(txUsed).WRITE()
	return inst
}

func (inst *WithdrawNativeInstruction) findFindTxUsedAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: withdraw
	seeds = append(seeds, []byte{byte(0x77), byte(0x69), byte(0x74), byte(0x68), byte(0x64), byte(0x72), byte(0x61), byte(0x77)})
	// arg: Hash
	hashSeed, err := ag_binary.MarshalBorsh(inst.Hash)
	if err != nil {
		return
	}
	seeds = append(seeds, hashSeed)
	// arg: BridgeId
	bridgeIdSeed, err := ag_binary.MarshalBorsh(inst.BridgeId)
	if err != nil {
		return
	}
	seeds = append(seeds, bridgeIdSeed)

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindTxUsedAddressWithBumpSeed calculates TxUsed account address with given seeds and a known bump seed.
func (inst *WithdrawNativeInstruction) FindTxUsedAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindTxUsedAddress(bumpSeed)
	return
}

func (inst *WithdrawNativeInstruction) MustFindTxUsedAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindTxUsedAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindTxUsedAddress finds TxUsed account address with given seeds.
func (inst *WithdrawNativeInstruction) FindTxUsedAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindTxUsedAddress(0)
	return
}

func (inst *WithdrawNativeInstruction) MustFindTxUsedAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindTxUsedAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetTxUsedAccount gets the "tx_used" account.
func (inst *WithdrawNativeInstruction) GetTxUsedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetSignerAccount sets the "signer" account.
func (inst *WithdrawNativeInstruction) SetSignerAccount(signer ag_solanago.PublicKey) *WithdrawNativeInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *WithdrawNativeInstruction) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *WithdrawNativeInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *WithdrawNativeInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *WithdrawNativeInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

func (inst WithdrawNativeInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_WithdrawNative,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst WithdrawNativeInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *WithdrawNativeInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeId == nil {
			return errors.New("BridgeId parameter is not set")
		}
		if inst.Hash == nil {
			return errors.New("Hash parameter is not set")
		}
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
		if inst.Nonce == nil {
			return errors.New("Nonce parameter is not set")
		}
		if inst.Signature == nil {
			return errors.New("Signature parameter is not set")
		}
		if inst.RecoveryId == nil {
			return errors.New("RecoveryId parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Receiver is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.TxUsed is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
	}
	return nil
}

func (inst *WithdrawNativeInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("WithdrawNative")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=6]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   BridgeId", *inst.BridgeId))
						paramsBranch.Child(ag_format.Param("       Hash", *inst.Hash))
						paramsBranch.Child(ag_format.Param("     Amount", *inst.Amount))
						paramsBranch.Child(ag_format.Param("      Nonce", *inst.Nonce))
						paramsBranch.Child(ag_format.Param("  Signature", *inst.Signature))
						paramsBranch.Child(ag_format.Param(" RecoveryId", *inst.RecoveryId))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=5]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("      receiver", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     authority", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       tx_used", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        signer", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("system_program", inst.AccountMetaSlice.Get(4)))
					})
				})
		})
}

func (obj WithdrawNativeInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeId` param:
	err = encoder.Encode(obj.BridgeId)
	if err != nil {
		return err
	}
	// Serialize `Hash` param:
	err = encoder.Encode(obj.Hash)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `Nonce` param:
	err = encoder.Encode(obj.Nonce)
	if err != nil {
		return err
	}
	// Serialize `Signature` param:
	err = encoder.Encode(obj.Signature)
	if err != nil {
		return err
	}
	// Serialize `RecoveryId` param:
	err = encoder.Encode(obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}
func (obj *WithdrawNativeInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeId`:
	err = decoder.Decode(&obj.BridgeId)
	if err != nil {
		return err
	}
	// Deserialize `Hash`:
	err = decoder.Decode(&obj.Hash)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `Nonce`:
	err = decoder.Decode(&obj.Nonce)
	if err != nil {
		return err
	}
	// Deserialize `Signature`:
	err = decoder.Decode(&obj.Signature)
	if err != nil {
		return err
	}
	// Deserialize `RecoveryId`:
	err = decoder.Decode(&obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}

// NewWithdrawNativeInstruction declares a new WithdrawNative instruction with the provided parameters and accounts.
func NewWithdrawNativeInstruction(
	// Parameters:
	bridge_id string,
	hash [32]uint8,
	amount uint64,
	nonce uint64,
	signature [64]uint8,
	recovery_id uint8,
	// Accounts:
	receiver ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	txUsed ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey) *WithdrawNativeInstruction {
	return NewWithdrawNativeInstructionBuilder().
		SetBridgeId(bridge_id).
		SetHash(hash).
		SetAmount(amount).
		SetNonce(nonce).
		SetSignature(signature).
		SetRecoveryId(recovery_id).
		SetReceiverAccount(receiver).
		SetAuthorityAccount(authority).
		SetTxUsedAccount(txUsed).
		SetSignerAccount(signer).
		SetSystemProgramAccount(systemProgram)
}
