// Code generated by https://github.com/alivers/anchor-go/internal. DO NOT EDIT.

package contract

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// WithdrawSpl is the `withdraw_spl` instruction.
type WithdrawSpl struct {
	BridgeId   *string
	Hash       *[32]uint8
	Amount     *uint64
	Uid        *[32]uint8
	Signature  *[64]uint8
	RecoveryId *uint8

	// [0] = [] mint
	//
	// [1] = [WRITE] spl_vault
	//
	// [2] = [WRITE] receiver
	//
	// [3] = [] authority
	//
	// [4] = [WRITE] tx_used
	//
	// [5] = [WRITE, SIGNER] signer
	//
	// [6] = [] system_program
	//
	// [7] = [] token_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewWithdrawSplInstructionBuilder creates a new `WithdrawSpl` instruction builder.
func NewWithdrawSplInstructionBuilder() *WithdrawSpl {
	nd := &WithdrawSpl{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	nd.AccountMetaSlice[6] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	return nd
}

// SetBridgeId sets the "bridge_id" parameter.
func (inst *WithdrawSpl) SetBridgeId(bridge_id string) *WithdrawSpl {
	inst.BridgeId = &bridge_id
	return inst
}

// SetHash sets the "hash" parameter.
func (inst *WithdrawSpl) SetHash(hash [32]uint8) *WithdrawSpl {
	inst.Hash = &hash
	return inst
}

// SetAmount sets the "amount" parameter.
func (inst *WithdrawSpl) SetAmount(amount uint64) *WithdrawSpl {
	inst.Amount = &amount
	return inst
}

// SetUid sets the "uid" parameter.
func (inst *WithdrawSpl) SetUid(uid [32]uint8) *WithdrawSpl {
	inst.Uid = &uid
	return inst
}

// SetSignature sets the "signature" parameter.
func (inst *WithdrawSpl) SetSignature(signature [64]uint8) *WithdrawSpl {
	inst.Signature = &signature
	return inst
}

// SetRecoveryId sets the "recovery_id" parameter.
func (inst *WithdrawSpl) SetRecoveryId(recovery_id uint8) *WithdrawSpl {
	inst.RecoveryId = &recovery_id
	return inst
}

// SetMintAccount sets the "mint" account.
func (inst *WithdrawSpl) SetMintAccount(mint ag_solanago.PublicKey) *WithdrawSpl {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *WithdrawSpl) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSplVaultAccount sets the "spl_vault" account.
func (inst *WithdrawSpl) SetSplVaultAccount(splVault ag_solanago.PublicKey) *WithdrawSpl {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(splVault).WRITE()
	return inst
}

// GetSplVaultAccount gets the "spl_vault" account.
func (inst *WithdrawSpl) GetSplVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst *WithdrawSpl) findSplVaultAddress(mint ag_solanago.PublicKey, bridgeId string, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: 0x7661756c74
	seeds = append(seeds, []byte{byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	seeds = append(seeds, mint.Bytes())
	{
		// path: bridge_id
		var res []byte
		res, err = ag_binary.MarshalBorsh(bridgeId)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// findSplVaultAddressWithBumpSeed calculates SplVault account address with given seeds and a known bump seed.
// pda program and seeds which refer to the instruction accounts or args should be provided as parameters.
func (inst *WithdrawSpl) findSplVaultAddressWithBumpSeed(mint ag_solanago.PublicKey, bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findSplVaultAddress(mint, bridgeId, bumpSeed)
	return
}
func (inst *WithdrawSpl) MustfindSplVaultAddressWithBumpSeed(mint ag_solanago.PublicKey, bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findSplVaultAddress(mint, bridgeId, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindSplVaultAddress finds SplVault account address with given seeds.
func (inst *WithdrawSpl) FindSplVaultAddress(mint ag_solanago.PublicKey, bridgeId string) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findSplVaultAddress(mint, bridgeId, 0)
	return
}
func (inst *WithdrawSpl) MustFindSplVaultAddress(mint ag_solanago.PublicKey, bridgeId string) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findSplVaultAddress(mint, bridgeId, 0)
	if err != nil {
		panic(err)
	}
	return
}

// SetReceiverAccount sets the "receiver" account.
func (inst *WithdrawSpl) SetReceiverAccount(receiver ag_solanago.PublicKey) *WithdrawSpl {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(receiver).WRITE()
	return inst
}

// GetReceiverAccount gets the "receiver" account.
func (inst *WithdrawSpl) GetReceiverAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *WithdrawSpl) SetAuthorityAccount(authority ag_solanago.PublicKey) *WithdrawSpl {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(authority)
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *WithdrawSpl) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst *WithdrawSpl) findAuthorityAddress(bridgeId string, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: 0x617574686f72697479
	seeds = append(seeds, []byte{byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})
	{
		// path: bridge_id
		var res []byte
		res, err = ag_binary.MarshalBorsh(bridgeId)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// findAuthorityAddressWithBumpSeed calculates Authority account address with given seeds and a known bump seed.
// pda program and seeds which refer to the instruction accounts or args should be provided as parameters.
func (inst *WithdrawSpl) findAuthorityAddressWithBumpSeed(bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findAuthorityAddress(bridgeId, bumpSeed)
	return
}
func (inst *WithdrawSpl) MustfindAuthorityAddressWithBumpSeed(bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findAuthorityAddress(bridgeId, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAuthorityAddress finds Authority account address with given seeds.
func (inst *WithdrawSpl) FindAuthorityAddress(bridgeId string) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findAuthorityAddress(bridgeId, 0)
	return
}
func (inst *WithdrawSpl) MustFindAuthorityAddress(bridgeId string) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findAuthorityAddress(bridgeId, 0)
	if err != nil {
		panic(err)
	}
	return
}

// SetTxUsedAccount sets the "tx_used" account.
func (inst *WithdrawSpl) SetTxUsedAccount(txUsed ag_solanago.PublicKey) *WithdrawSpl {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(txUsed).WRITE()
	return inst
}

// GetTxUsedAccount gets the "tx_used" account.
func (inst *WithdrawSpl) GetTxUsedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

func (inst *WithdrawSpl) findTxUsedAddress(hash [32]uint8, bridgeId string, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: 0x7769746864726177
	seeds = append(seeds, []byte{byte(0x77), byte(0x69), byte(0x74), byte(0x68), byte(0x64), byte(0x72), byte(0x61), byte(0x77)})
	{
		// path: hash
		var res []byte
		res, err = ag_binary.MarshalBorsh(hash)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}
	{
		// path: bridge_id
		var res []byte
		res, err = ag_binary.MarshalBorsh(bridgeId)
		if err != nil {
			return
		}
		seeds = append(seeds, res)
	}

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// findTxUsedAddressWithBumpSeed calculates TxUsed account address with given seeds and a known bump seed.
// pda program and seeds which refer to the instruction accounts or args should be provided as parameters.
func (inst *WithdrawSpl) findTxUsedAddressWithBumpSeed(hash [32]uint8, bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findTxUsedAddress(hash, bridgeId, bumpSeed)
	return
}
func (inst *WithdrawSpl) MustfindTxUsedAddressWithBumpSeed(hash [32]uint8, bridgeId string, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findTxUsedAddress(hash, bridgeId, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindTxUsedAddress finds TxUsed account address with given seeds.
func (inst *WithdrawSpl) FindTxUsedAddress(hash [32]uint8, bridgeId string) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findTxUsedAddress(hash, bridgeId, 0)
	return
}
func (inst *WithdrawSpl) MustFindTxUsedAddress(hash [32]uint8, bridgeId string) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findTxUsedAddress(hash, bridgeId, 0)
	if err != nil {
		panic(err)
	}
	return
}

// SetSignerAccount sets the "signer" account.
func (inst *WithdrawSpl) SetSignerAccount(signer ag_solanago.PublicKey) *WithdrawSpl {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *WithdrawSpl) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *WithdrawSpl) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *WithdrawSpl {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *WithdrawSpl) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *WithdrawSpl) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *WithdrawSpl {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *WithdrawSpl) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst WithdrawSpl) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_WithdrawSpl,
	}}
}

func (inst *WithdrawSpl) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeId == nil {
			return errors.New("BridgeId parameter is not set")
		}
		if inst.Hash == nil {
			return errors.New("Hash parameter is not set")
		}
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
		if inst.Uid == nil {
			return errors.New("Uid parameter is not set")
		}
		if inst.Signature == nil {
			return errors.New("Signature parameter is not set")
		}
		if inst.RecoveryId == nil {
			return errors.New("RecoveryId parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SplVault is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Receiver is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.TxUsed is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst WithdrawSpl) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *WithdrawSpl) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("WithdrawSpl")).
				ParentFunc(func(instructionBranch ag_treeout.Branches) {
					// Parameters of the instruction:
					instructionBranch.Child("Params[len=6]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   BridgeId", *inst.BridgeId))
						paramsBranch.Child(ag_format.Param("       Hash", *inst.Hash))
						paramsBranch.Child(ag_format.Param("     Amount", *inst.Amount))
						paramsBranch.Child(ag_format.Param("        Uid", *inst.Uid))
						paramsBranch.Child(ag_format.Param("  Signature", *inst.Signature))
						paramsBranch.Child(ag_format.Param(" RecoveryId", *inst.RecoveryId))
					})
					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          mint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     spl_vault", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("      receiver", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("     authority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("       tx_used", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        signer", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("system_program", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta(" token_program", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj WithdrawSpl) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeId` param:
	err = encoder.Encode(obj.BridgeId)
	if err != nil {
		return err
	}
	// Serialize `Hash` param:
	err = encoder.Encode(obj.Hash)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `Uid` param:
	err = encoder.Encode(obj.Uid)
	if err != nil {
		return err
	}
	// Serialize `Signature` param:
	err = encoder.Encode(obj.Signature)
	if err != nil {
		return err
	}
	// Serialize `RecoveryId` param:
	err = encoder.Encode(obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}

func (obj *WithdrawSpl) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeId`:
	err = decoder.Decode(&obj.BridgeId)
	if err != nil {
		return err
	}
	// Deserialize `Hash`:
	err = decoder.Decode(&obj.Hash)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `Uid`:
	err = decoder.Decode(&obj.Uid)
	if err != nil {
		return err
	}
	// Deserialize `Signature`:
	err = decoder.Decode(&obj.Signature)
	if err != nil {
		return err
	}
	// Deserialize `RecoveryId`:
	err = decoder.Decode(&obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}

// NewWithdrawSplInstruction declares a new WithdrawSpl instruction with the provided parameters and accounts.
func NewWithdrawSplInstruction(
	// Parameters:
	bridge_id string,
	hash [32]uint8,
	amount uint64,
	uid [32]uint8,
	signature [64]uint8,
	recovery_id uint8,
	// Accounts:
	mint ag_solanago.PublicKey,
	splVault ag_solanago.PublicKey,
	receiver ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	txUsed ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
) *WithdrawSpl {
	return NewWithdrawSplInstructionBuilder().
		SetBridgeId(bridge_id).
		SetHash(hash).
		SetAmount(amount).
		SetUid(uid).
		SetSignature(signature).
		SetRecoveryId(recovery_id).
		SetMintAccount(mint).
		SetSplVaultAccount(splVault).
		SetReceiverAccount(receiver).
		SetAuthorityAccount(authority).
		SetTxUsedAccount(txUsed).
		SetSignerAccount(signer).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram)
}
