// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package contract

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// WithdrawSpl is the `withdraw_spl` instruction.
type WithdrawSplInstruction struct {
	BridgeId   *string
	Hash       *[32]uint8
	Amount     *uint64
	Nonce      *uint64
	Signature  *[64]uint8
	RecoveryId *uint8

	// [0] = [] mint
	//
	// [1] = [WRITE] spl_vault
	//
	// [2] = [WRITE] receiver
	//
	// [3] = [] authority
	//
	// [4] = [WRITE] tx_used
	//
	// [5] = [WRITE, SIGNER] signer
	//
	// [6] = [] system_program
	//
	// [7] = [] token_program
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewWithdrawSplInstructionBuilder creates a new `WithdrawSplInstruction` instruction builder.
func NewWithdrawSplInstructionBuilder() *WithdrawSplInstruction {
	nd := &WithdrawSplInstruction{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 8),
	}
	nd.AccountMetaSlice[6] = ag_solanago.Meta(Addresses["11111111111111111111111111111111"])
	return nd
}

// SetBridgeId sets the "bridge_id" parameter.
func (inst *WithdrawSplInstruction) SetBridgeId(bridge_id string) *WithdrawSplInstruction {
	inst.BridgeId = &bridge_id
	return inst
}

// SetHash sets the "hash" parameter.
func (inst *WithdrawSplInstruction) SetHash(hash [32]uint8) *WithdrawSplInstruction {
	inst.Hash = &hash
	return inst
}

// SetAmount sets the "amount" parameter.
func (inst *WithdrawSplInstruction) SetAmount(amount uint64) *WithdrawSplInstruction {
	inst.Amount = &amount
	return inst
}

// SetNonce sets the "nonce" parameter.
func (inst *WithdrawSplInstruction) SetNonce(nonce uint64) *WithdrawSplInstruction {
	inst.Nonce = &nonce
	return inst
}

// SetSignature sets the "signature" parameter.
func (inst *WithdrawSplInstruction) SetSignature(signature [64]uint8) *WithdrawSplInstruction {
	inst.Signature = &signature
	return inst
}

// SetRecoveryId sets the "recovery_id" parameter.
func (inst *WithdrawSplInstruction) SetRecoveryId(recovery_id uint8) *WithdrawSplInstruction {
	inst.RecoveryId = &recovery_id
	return inst
}

// SetMintAccount sets the "mint" account.
func (inst *WithdrawSplInstruction) SetMintAccount(mint ag_solanago.PublicKey) *WithdrawSplInstruction {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *WithdrawSplInstruction) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetSplVaultAccount sets the "spl_vault" account.
func (inst *WithdrawSplInstruction) SetSplVaultAccount(splVault ag_solanago.PublicKey) *WithdrawSplInstruction {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(splVault).WRITE()
	return inst
}

func (inst *WithdrawSplInstruction) findFindSplVaultAddress(mint ag_solanago.PublicKey, knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: vault
	seeds = append(seeds, []byte{byte(0x76), byte(0x61), byte(0x75), byte(0x6c), byte(0x74)})
	// path: mint
	seeds = append(seeds, mint.Bytes())
	// arg: BridgeId
	bridgeIdSeed, err := ag_binary.MarshalBorsh(inst.BridgeId)
	if err != nil {
		return
	}
	seeds = append(seeds, bridgeIdSeed)

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindSplVaultAddressWithBumpSeed calculates SplVault account address with given seeds and a known bump seed.
func (inst *WithdrawSplInstruction) FindSplVaultAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindSplVaultAddress(mint, bumpSeed)
	return
}

func (inst *WithdrawSplInstruction) MustFindSplVaultAddressWithBumpSeed(mint ag_solanago.PublicKey, bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSplVaultAddress(mint, bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindSplVaultAddress finds SplVault account address with given seeds.
func (inst *WithdrawSplInstruction) FindSplVaultAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindSplVaultAddress(mint, 0)
	return
}

func (inst *WithdrawSplInstruction) MustFindSplVaultAddress(mint ag_solanago.PublicKey) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindSplVaultAddress(mint, 0)
	if err != nil {
		panic(err)
	}
	return
}

// GetSplVaultAccount gets the "spl_vault" account.
func (inst *WithdrawSplInstruction) GetSplVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetReceiverAccount sets the "receiver" account.
func (inst *WithdrawSplInstruction) SetReceiverAccount(receiver ag_solanago.PublicKey) *WithdrawSplInstruction {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(receiver).WRITE()
	return inst
}

// GetReceiverAccount gets the "receiver" account.
func (inst *WithdrawSplInstruction) GetReceiverAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *WithdrawSplInstruction) SetAuthorityAccount(authority ag_solanago.PublicKey) *WithdrawSplInstruction {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(authority)
	return inst
}

func (inst *WithdrawSplInstruction) findFindAuthorityAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: authority
	seeds = append(seeds, []byte{byte(0x61), byte(0x75), byte(0x74), byte(0x68), byte(0x6f), byte(0x72), byte(0x69), byte(0x74), byte(0x79)})
	// arg: BridgeId
	bridgeIdSeed, err := ag_binary.MarshalBorsh(inst.BridgeId)
	if err != nil {
		return
	}
	seeds = append(seeds, bridgeIdSeed)

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindAuthorityAddressWithBumpSeed calculates Authority account address with given seeds and a known bump seed.
func (inst *WithdrawSplInstruction) FindAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindAuthorityAddress(bumpSeed)
	return
}

func (inst *WithdrawSplInstruction) MustFindAuthorityAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAuthorityAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindAuthorityAddress finds Authority account address with given seeds.
func (inst *WithdrawSplInstruction) FindAuthorityAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindAuthorityAddress(0)
	return
}

func (inst *WithdrawSplInstruction) MustFindAuthorityAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindAuthorityAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetAuthorityAccount gets the "authority" account.
func (inst *WithdrawSplInstruction) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetTxUsedAccount sets the "tx_used" account.
func (inst *WithdrawSplInstruction) SetTxUsedAccount(txUsed ag_solanago.PublicKey) *WithdrawSplInstruction {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(txUsed).WRITE()
	return inst
}

func (inst *WithdrawSplInstruction) findFindTxUsedAddress(knownBumpSeed uint8) (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	var seeds [][]byte
	// const: withdraw
	seeds = append(seeds, []byte{byte(0x77), byte(0x69), byte(0x74), byte(0x68), byte(0x64), byte(0x72), byte(0x61), byte(0x77)})
	// arg: Hash
	hashSeed, err := ag_binary.MarshalBorsh(inst.Hash)
	if err != nil {
		return
	}
	seeds = append(seeds, hashSeed)
	// arg: BridgeId
	bridgeIdSeed, err := ag_binary.MarshalBorsh(inst.BridgeId)
	if err != nil {
		return
	}
	seeds = append(seeds, bridgeIdSeed)

	if knownBumpSeed != 0 {
		seeds = append(seeds, []byte{byte(bumpSeed)})
		pda, err = ag_solanago.CreateProgramAddress(seeds, ProgramID)
	} else {
		pda, bumpSeed, err = ag_solanago.FindProgramAddress(seeds, ProgramID)
	}
	return
}

// FindTxUsedAddressWithBumpSeed calculates TxUsed account address with given seeds and a known bump seed.
func (inst *WithdrawSplInstruction) FindTxUsedAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey, err error) {
	pda, _, err = inst.findFindTxUsedAddress(bumpSeed)
	return
}

func (inst *WithdrawSplInstruction) MustFindTxUsedAddressWithBumpSeed(bumpSeed uint8) (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindTxUsedAddress(bumpSeed)
	if err != nil {
		panic(err)
	}
	return
}

// FindTxUsedAddress finds TxUsed account address with given seeds.
func (inst *WithdrawSplInstruction) FindTxUsedAddress() (pda ag_solanago.PublicKey, bumpSeed uint8, err error) {
	pda, bumpSeed, err = inst.findFindTxUsedAddress(0)
	return
}

func (inst *WithdrawSplInstruction) MustFindTxUsedAddress() (pda ag_solanago.PublicKey) {
	pda, _, err := inst.findFindTxUsedAddress(0)
	if err != nil {
		panic(err)
	}
	return
}

// GetTxUsedAccount gets the "tx_used" account.
func (inst *WithdrawSplInstruction) GetTxUsedAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetSignerAccount sets the "signer" account.
func (inst *WithdrawSplInstruction) SetSignerAccount(signer ag_solanago.PublicKey) *WithdrawSplInstruction {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *WithdrawSplInstruction) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *WithdrawSplInstruction) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *WithdrawSplInstruction {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *WithdrawSplInstruction) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *WithdrawSplInstruction) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *WithdrawSplInstruction {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *WithdrawSplInstruction) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

func (inst WithdrawSplInstruction) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_WithdrawSpl,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst WithdrawSplInstruction) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *WithdrawSplInstruction) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.BridgeId == nil {
			return errors.New("BridgeId parameter is not set")
		}
		if inst.Hash == nil {
			return errors.New("Hash parameter is not set")
		}
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
		if inst.Nonce == nil {
			return errors.New("Nonce parameter is not set")
		}
		if inst.Signature == nil {
			return errors.New("Signature parameter is not set")
		}
		if inst.RecoveryId == nil {
			return errors.New("RecoveryId parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.SplVault is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Receiver is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.TxUsed is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *WithdrawSplInstruction) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("WithdrawSpl")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=6]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("   BridgeId", *inst.BridgeId))
						paramsBranch.Child(ag_format.Param("       Hash", *inst.Hash))
						paramsBranch.Child(ag_format.Param("     Amount", *inst.Amount))
						paramsBranch.Child(ag_format.Param("      Nonce", *inst.Nonce))
						paramsBranch.Child(ag_format.Param("  Signature", *inst.Signature))
						paramsBranch.Child(ag_format.Param(" RecoveryId", *inst.RecoveryId))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=8]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("          mint", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     spl_vault", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("      receiver", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("     authority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("       tx_used", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("        signer", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("system_program", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta(" token_program", inst.AccountMetaSlice.Get(7)))
					})
				})
		})
}

func (obj WithdrawSplInstruction) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `BridgeId` param:
	err = encoder.Encode(obj.BridgeId)
	if err != nil {
		return err
	}
	// Serialize `Hash` param:
	err = encoder.Encode(obj.Hash)
	if err != nil {
		return err
	}
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	// Serialize `Nonce` param:
	err = encoder.Encode(obj.Nonce)
	if err != nil {
		return err
	}
	// Serialize `Signature` param:
	err = encoder.Encode(obj.Signature)
	if err != nil {
		return err
	}
	// Serialize `RecoveryId` param:
	err = encoder.Encode(obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}
func (obj *WithdrawSplInstruction) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `BridgeId`:
	err = decoder.Decode(&obj.BridgeId)
	if err != nil {
		return err
	}
	// Deserialize `Hash`:
	err = decoder.Decode(&obj.Hash)
	if err != nil {
		return err
	}
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	// Deserialize `Nonce`:
	err = decoder.Decode(&obj.Nonce)
	if err != nil {
		return err
	}
	// Deserialize `Signature`:
	err = decoder.Decode(&obj.Signature)
	if err != nil {
		return err
	}
	// Deserialize `RecoveryId`:
	err = decoder.Decode(&obj.RecoveryId)
	if err != nil {
		return err
	}
	return nil
}

// NewWithdrawSplInstruction declares a new WithdrawSpl instruction with the provided parameters and accounts.
func NewWithdrawSplInstruction(
	// Parameters:
	bridge_id string,
	hash [32]uint8,
	amount uint64,
	nonce uint64,
	signature [64]uint8,
	recovery_id uint8,
	// Accounts:
	mint ag_solanago.PublicKey,
	splVault ag_solanago.PublicKey,
	receiver ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	txUsed ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *WithdrawSplInstruction {
	return NewWithdrawSplInstructionBuilder().
		SetBridgeId(bridge_id).
		SetHash(hash).
		SetAmount(amount).
		SetNonce(nonce).
		SetSignature(signature).
		SetRecoveryId(recovery_id).
		SetMintAccount(mint).
		SetSplVaultAccount(splVault).
		SetReceiverAccount(receiver).
		SetAuthorityAccount(authority).
		SetTxUsedAccount(txUsed).
		SetSignerAccount(signer).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram)
}
