// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api_server.proto

package types

import (
	types "github.com/Bridgeless-Project/tss-svc/internal/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/anypb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckWithdrawalResponse struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	DepositIdentifier    *types.DepositIdentifier    `protobuf:"bytes,1,opt,name=deposit_identifier,json=depositIdentifier,proto3" json:"deposit_identifier,omitempty"`
	TransferData         *types.TransferData         `protobuf:"bytes,2,opt,name=transfer_data,json=transferData,proto3" json:"transfer_data,omitempty"`
	WithdrawalStatus     types.WithdrawalStatus      `protobuf:"varint,3,opt,name=withdrawal_status,json=withdrawalStatus,proto3,enum=deposit.WithdrawalStatus" json:"withdrawal_status,omitempty"`
	WithdrawalIdentifier *types.WithdrawalIdentifier `protobuf:"bytes,4,opt,name=withdrawal_identifier,json=withdrawalIdentifier,proto3,oneof" json:"withdrawal_identifier,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CheckWithdrawalResponse) Reset() {
	*x = CheckWithdrawalResponse{}
	mi := &file_api_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckWithdrawalResponse) ProtoMessage() {}

func (x *CheckWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*CheckWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_api_server_proto_rawDescGZIP(), []int{0}
}

func (x *CheckWithdrawalResponse) GetDepositIdentifier() *types.DepositIdentifier {
	if x != nil {
		return x.DepositIdentifier
	}
	return nil
}

func (x *CheckWithdrawalResponse) GetTransferData() *types.TransferData {
	if x != nil {
		return x.TransferData
	}
	return nil
}

func (x *CheckWithdrawalResponse) GetWithdrawalStatus() types.WithdrawalStatus {
	if x != nil {
		return x.WithdrawalStatus
	}
	return types.WithdrawalStatus(0)
}

func (x *CheckWithdrawalResponse) GetWithdrawalIdentifier() *types.WithdrawalIdentifier {
	if x != nil {
		return x.WithdrawalIdentifier
	}
	return nil
}

var File_api_server_proto protoreflect.FileDescriptor

const file_api_server_proto_rawDesc = "" +
	"\n" +
	"\x10api_server.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x19google/protobuf/any.proto\x1a\rdeposit.proto\"\xdb\x02\n" +
	"\x17CheckWithdrawalResponse\x12I\n" +
	"\x12deposit_identifier\x18\x01 \x01(\v2\x1a.deposit.DepositIdentifierR\x11depositIdentifier\x12:\n" +
	"\rtransfer_data\x18\x02 \x01(\v2\x15.deposit.TransferDataR\ftransferData\x12F\n" +
	"\x11withdrawal_status\x18\x03 \x01(\x0e2\x19.deposit.WithdrawalStatusR\x10withdrawalStatus\x12W\n" +
	"\x15withdrawal_identifier\x18\x04 \x01(\v2\x1d.deposit.WithdrawalIdentifierH\x00R\x14withdrawalIdentifier\x88\x01\x01B\x18\n" +
	"\x16_withdrawal_identifier2\xde\x01\n" +
	"\x03API\x12Z\n" +
	"\x10SubmitWithdrawal\x12\x1a.deposit.DepositIdentifier\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f:\x01*\"\a/submit\x12{\n" +
	"\x0fCheckWithdrawal\x12\x1a.deposit.DepositIdentifier\x1a\x1c.api.CheckWithdrawalResponse\".\x82\xd3\xe4\x93\x02(\x12&/check/{chain_id}/{tx_hash}/{tx_nonce}B1Z/github.com/Bridgeless-Project/tss-svc/internal/api/typesb\x06proto3"

var (
	file_api_server_proto_rawDescOnce sync.Once
	file_api_server_proto_rawDescData []byte
)

func file_api_server_proto_rawDescGZIP() []byte {
	file_api_server_proto_rawDescOnce.Do(func() {
		file_api_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_server_proto_rawDesc), len(file_api_server_proto_rawDesc)))
	})
	return file_api_server_proto_rawDescData
}

var file_api_server_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_server_proto_goTypes = []any{
	(*CheckWithdrawalResponse)(nil),    // 0: api.CheckWithdrawalResponse
	(*types.DepositIdentifier)(nil),    // 1: deposit.DepositIdentifier
	(*types.TransferData)(nil),         // 2: deposit.TransferData
	(types.WithdrawalStatus)(0),        // 3: deposit.WithdrawalStatus
	(*types.WithdrawalIdentifier)(nil), // 4: deposit.WithdrawalIdentifier
	(*emptypb.Empty)(nil),              // 5: google.protobuf.Empty
}
var file_api_server_proto_depIdxs = []int32{
	1, // 0: api.CheckWithdrawalResponse.deposit_identifier:type_name -> deposit.DepositIdentifier
	2, // 1: api.CheckWithdrawalResponse.transfer_data:type_name -> deposit.TransferData
	3, // 2: api.CheckWithdrawalResponse.withdrawal_status:type_name -> deposit.WithdrawalStatus
	4, // 3: api.CheckWithdrawalResponse.withdrawal_identifier:type_name -> deposit.WithdrawalIdentifier
	1, // 4: api.API.SubmitWithdrawal:input_type -> deposit.DepositIdentifier
	1, // 5: api.API.CheckWithdrawal:input_type -> deposit.DepositIdentifier
	5, // 6: api.API.SubmitWithdrawal:output_type -> google.protobuf.Empty
	0, // 7: api.API.CheckWithdrawal:output_type -> api.CheckWithdrawalResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_server_proto_init() }
func file_api_server_proto_init() {
	if File_api_server_proto != nil {
		return
	}
	file_api_server_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_server_proto_rawDesc), len(file_api_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_server_proto_goTypes,
		DependencyIndexes: file_api_server_proto_depIdxs,
		MessageInfos:      file_api_server_proto_msgTypes,
	}.Build()
	File_api_server_proto = out.File
	file_api_server_proto_goTypes = nil
	file_api_server_proto_depIdxs = nil
}
