## Logger configuration
log:
  ## Log level: debug, info, warn, error, fatal
  level: debug
  ## Disable Sentry integration
  disable_sentry: true

## Database configuration
db:
  ## Database URL connection string
  url:

## gRPC listener configuration
listener-grpc:
  ## gRPC listener address
  addr: :8012
listener-http:
  addr: :8084

## Parties configuration
parties:
  ## List of parties
  list:
    ## Concrete party configuration
    - core_address: bridge123ex5u9qqmlyzzff278ncsn7rwh65ks0urjyzn
      connection: conn

## Chain list configuration
chains:
  list:
    ## Chain ID
    - id: "test1"
      ## RPC endpoint
      rpc: "your_rpc_endpoint_here"
      ## Bridge contract address
      bridge_addresses: "test_address"
      ## Number of confirmations required for the withdrawal to be considered final
      confirmations: 1
      type: "type1"

## TSS configuration
tss:
  start_time: "2025-01-21 15:28:00"
  session_id: 123
  threshold: 2

## Bridge Core connector configuration
core_connector:
  ## Core RPC connection settings
  connection:
    ## Core RPC endpoint for queries and transactions
    addr: "rpc"
    ## Whether to enable TLS connection or not
    enable_tls: false
  ## General Core settings
  settings:
    chain_id: "00000"
    denom: "denom"
    min_gas_price: 0