## Logger configuration
log:
  ## Log level: debug, info, warn, error, fatal
  level: debug
  ## Disable Sentry integration
  disable_sentry: true

## Database configuration
db:
  ## Database URL connection string
  url:

## gRPC listener configuration
listener-grpc:
  ## gRPC listener address
  addr: :8012
listener-http:
  addr: :8084

## Parties configuration
parties:
  ## List of parties
  list:
    ## Party 1
    - core_address: bridge123ex5u9qqmlyzzff278ncsn7rwh65ks0urjyzn
      connection: conn
      pubkey: pub

## Chain list configuration
chains:
  list:
    ## Chain ID
    - id: "test1"
      ## RPC endpoint
      rpc: "your_rpc_endpoint_here"
      ## Bridge contract address
      bridge_addresses: "test_address"
      ## Number of confirmations required for the deposit to be considered final
      confirmations: 1
      type: "type1"

## TSS configuration
tss:
  ## Keygen configuration
  keygen:
    ## Keygen start time
    start_time: "2025-01-08 00:21:20"
    ## Keygen session ID
    session_id: abcd
  ## Signing configuration
  signing:
    start_time: "2025-01-21 15:28:00"
    session_id: abcd
    threshold: 2

core_connector:
  connection:
    addr: "rpc"
    enable_tls: false
  settings:
    account_private_key: "private"
    chain_id: "00000"
    denom: "denom"
    min_gas_price: 0